---
sidebar: sidebar 
permalink: codebox-automation.html 
keywords: codebox, automation 
summary: 'Codebox é um copiloto de infraestrutura como código (IAC) que ajuda desenvolvedores e DevOps a gerar o código necessário para executar qualquer operação suportada pela fábrica de cargas de trabalho. O Codebox está alinhado com os modos de operação de fábrica da carga de trabalho (Basic, Read, Automate) e define um caminho claro para a prontidão da execução, bem como fornece um catálogo de automação para rápida reutilização futura.' 
---
= Saiba mais sobre a automação do codebox
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Codebox é um copiloto de infraestrutura como código (IAC) que ajuda desenvolvedores e DevOps a gerar o código necessário para executar qualquer operação suportada pela fábrica de cargas de trabalho. O Codebox está alinhado com os modos de operação de fábrica da carga de trabalho (Basic, Read and Automate) e define um caminho claro para a prontidão da execução, bem como fornece um catálogo de automação para rápida reutilização futura.



== Recursos do Codebox

O Codebox fornece dois recursos principais do IAC:

* _Codebox Viewer_ mostra o IAC que é gerado por uma operação de fluxo de trabalho específica, combinando entradas e seleções do assistente gráfico ou da interface de bate-papo conversacional. Embora o Codebox Viewer suporte codificação de cores para fácil navegação e análise, ele não permite edição - apenas copiar ou salvar código para o Catálogo de Automação.
* _Codebox Automation Catalog_ mostra todos os trabalhos IAC salvos, permitindo que você facilmente os referencie para uso futuro. Os trabalhos de catálogo de automação são salvos como modelos e mostrados no contexto dos recursos que se aplicam a eles.


Além disso, ao configurar as credenciais de fábrica da carga de trabalho, o Codebox exibe dinamicamente as permissões da AWS necessárias para criar políticas do IAM. As permissões são fornecidas para cada funcionalidade de fábrica de workload que você planeja usar (bancos de dados, AI, FSX for ONTAP, etc.) e são personalizadas com base se os usuários da política obterão permissões somente leitura ou permissões completas de operação. Basta copiar as permissões do Codebox e colá-las no Console de Gerenciamento da AWS para que a fábrica de carga de trabalho tenha as permissões corretas para gerenciar suas cargas de trabalho.



== Formatos de código suportados

Os formatos de código suportados incluem:

* APIs REST de fábrica de workload
* CLI DA AWS
* AWS CloudFormation


link:use-codebox.html["Saiba como usar o Codebox"].
