---
sidebar: sidebar 
permalink: console-experiences.html 
keywords: console, consoles, access, saas, Workload Factory, bluexp, NetApp Workload Factory, NetApp Console 
summary: O NetApp Workload Factory pode ser acessado por meio de dois consoles baseados na Web. 
---
= Experiências de console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O NetApp Workload Factory pode ser acessado por meio de dois consoles baseados na Web.  Saiba como acessar o Workload Factory usando o console do Workload Factory e o NetApp Console.

* * NetApp Console*: Oferece uma experiência híbrida onde você pode gerenciar seus sistemas de arquivos FSx para ONTAP e cargas de trabalho em execução no Amazon FSx for NetApp ONTAP no mesmo lugar.
* *Console do Workload Factory*: Oferece uma experiência dedicada do Workload Factory focada em cargas de trabalho em execução no Amazon FSx for NetApp ONTAP.




== Acesse o Workload Factory no console do NetApp

Você pode acessar o Workload Factory no NetApp Console.  Além de usar o Workload Factory para recursos de armazenamento e carga de trabalho da AWS, você também pode acessar outros serviços de dados, como NetApp Copy and Sync, NetApp Digital Wallet e muito mais.

.Passos
. Faça login nolink:https://console.netapp.com["Console NetApp"^] .
. No menu do NetApp Console, selecione *Cargas de trabalho* e depois *Visão geral*.




== Acesse o Workload Factory no console do Workload Factory

Você pode acessar o Workload Factory no console do Workload Factory.

.Passo
. Faça login nolink:https://console.workloads.netapp.com["Console da Workload Factory"^] .

