---
sidebar: sidebar 
permalink: log-in.html 
keywords: logging in, log in, sign in, signing in, user account, login with netapp, log in with netapp, sign up, create account 
summary: Depois de se inscrever no Workload Factory, você pode fazer login a qualquer momento no console baseado na web para começar a gerenciar suas cargas de trabalho e o FSx para sistemas de arquivos ONTAP . 
---
= Efetue login no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Depois de se inscrever no NetApp Workload Factory, você pode efetuar login a qualquer momento no console baseado na Web para começar a gerenciar suas cargas de trabalho e o FSx para sistemas de arquivos ONTAP .

.Sobre esta tarefa
Você pode efetuar login no console web do Workload Factory usando uma das seguintes opções:

* Suas credenciais existentes do site de suporte da NetApp (NSS)
* Um login na nuvem do NetApp usando seu endereço de e-mail e uma senha


.Passos
. Abra um navegador da web e vá para o https://console.workloads.netapp.com["Console da Workload Factory"^] .
. Na página *Log in*, insira o endereço de e-mail associado ao seu login.
. Dependendo do método de autenticação associado ao seu login, você será solicitado a inserir suas credenciais:
+
** Credenciais de nuvem do NetApp: Insira sua senha
** Usuário federado: Insira suas credenciais de identidade federada
** Conta do site de suporte da NetApp: Insira suas credenciais do site de suporte da NetApp


. Selecione *Iniciar sessão*.
+
Se você já fez login com sucesso anteriormente, verá a página inicial do Workload Factory e estará usando a conta padrão.

+
Se esta for a primeira vez que você se logou, você será direcionado para a página *conta*.

+
** Se você é membro de uma única conta, selecione *continuar*.
** Se você for membro de várias contas, selecione a conta e selecione *continuar*.




.Resultado
Agora você está conectado e pode começar a usar o Workload Factory para gerenciar sistemas de arquivos FSx para ONTAP e suas cargas de trabalho.
