---
settings:
  name: Setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de configuração e administração
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
  - title: Comece agora
    entries:
    - title: Aprenda o básico
      entries:
      - title: Saiba mais sobre o NetApp Workload Factory
        url: "/workload-factory-overview.html"
      - title: Modos operacionais
        url: "/operational-modes.html"
      - title: Experiências de console
        url: "/console-experiences.html"
      - title: Permissões
        url: "/permissions-reference.html"
    - title: Início rápido
      url: "/quick-start.html"
    - title: Inscreva-se no Workload Factory
      url: "/sign-up-saas.html"
    - title: Adicionar credenciais da AWS
      url: "/add-credentials.html"
    - title: Otimize cargas de trabalho com o Workload Factory
      url: "/whats-next.html"
  - title: Administrar Fábrica de Carga de Trabalho
    entries:
    - title: Efetue login no Workload Factory
      url: "/log-in.html"
    - title: Gerenciar contas de serviço
      url: "/manage-service-accounts.html"
    - title: Configurar notificações
      url: "/configure-notifications.html"
    - title: Automatize tarefas usando Codebox
      entries:
      - title: Saiba mais sobre Codebox
        url: "/codebox-automation.html"
      - title: Use Codebox para gerar código
        url: "/use-codebox.html"
    - title: Use o CloudShell
      url: "/use-cloudshell.html"
    - title: Remover credenciais
      url: "/manage-credentials.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/support-registration.html"
    - title: Obtenha ajuda
      url: "/get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
