---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: O Workload Factory analisa as configurações de cargas de trabalho em busca de confiabilidade, segurança, excelência operacional, otimização de custos e eficiência de desempenho, fornecendo insights e recomendações para ajudá-lo a alcançar a excelência operacional. 
---
= Crie e opere cargas de trabalho bem arquitetadas com NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory, o NetApp management suite para Amazon FSx for NetApp ONTAP, ajuda você a manter e operar configurações de cargas de trabalho confiáveis, seguras, eficientes e econômicas que estejam alinhadas ao AWS Well-Architected Framework. Workload Factory fornece análise diária de suas cargas de trabalho, recomendações e correções automáticas para promover operações saudáveis de cargas de trabalho. Ao automatizar esse processo, Workload Factory minimiza erros humanos e garante consistência no gerenciamento de cargas de trabalho.



== Como funciona

O Workload Factory analisa diariamente suas cargas de trabalho em execução em implantações de sistemas de arquivos Amazon FSx for NetApp ONTAP. A análise fornece status bem arquitetado, insights e recomendações.

Após a conclusão da análise diária, as configurações aparecem como "otimizadas" ou "não otimizadas" no painel de controle do Well-architected para a implantação. Você encontrará a pontuação total de otimização, problemas de configuração por categoria e uma lista de problemas de configuração e recomendações. Você pode consultar as recomendações para problemas de configuração. Alguns problemas podem ser corrigidos automaticamente pelo Workload Factory, enquanto outros exigem intervenção manual. Nesse caso, o Workload Factory fornece instruções detalhadas para ajudá-lo a implementar as alterações recomendadas.

Você pode descartar a análise de configurações que não se aplicam aos seus ambientes. Isso evita alertas desnecessários e resultados de otimização imprecisos. Ao descartar uma análise de configuração específica, Workload Factory não inclui a configuração na pontuação total de otimização.



== Por que isso importa

O Workload Factory aplica as melhores práticas a grandes ambientes de armazenamento, banco de dados e VMware, combinando avaliação contínua com insights de recomendações e remediação. As correções automatizadas aplicadas no console do Workload Factory reduzem erros humanos, garantem gerenciamento uniforme e preservam o desempenho e a confiabilidade em toda a sua infraestrutura de cargas de trabalho.



== Comece a usar o Workload Factory para detectar e corrigir configurações incorretas de workload.

Para começar a usar o Workload Factory, inscreva-se, adicione credenciais e estabeleça conectividade para gerenciar recursos da AWS e otimizar cargas de trabalho usando Amazon FSx for NetApp ONTAP.

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["Início rápido"]



== Informações relacionadas

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementar um FSx bem arquitetado para sistemas de arquivos ONTAP."^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar cargas de trabalho de banco de dados bem arquitetadas"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implemente configurações Exchange Virtual Server bem arquitetadas"^]

